char_starting_location: [-0.3, -0.2, -0.5]
bvh_projection_bodypart_groups:
- bvh_joint_names:
  - RightShoulder
  - RightArm
  - RightForeArm
  - RightHand
  - RightHandEnd
  - LeftShoulder
  - LeftArm
  - LeftForeArm
  - LeftHand
  - LeftHandEnd
  method: pca
  name: Upper Limbs
- bvh_joint_names:
  - RightUpLeg
  - RightLeg
  - RightFoot
  - RightToeBase
  - LeftUpLeg
  - LeftLeg
  - LeftFoot
  - LeftToeBase
  method: pca
  name: Lower Limbs
- bvh_joint_names:
  - Hips
  - Spine
  - Spine1
  - Spine2
  - Spine3
  - Neck
  - Head
  method: frontal
  name: Trunk
char_bodypart_groups:
- bvh_depth_drivers:
  - Hips
  char_joints:
  - hip
  - torso
  - neck
- bvh_depth_drivers:
  - LeftFoot
  char_joints:
  - left_knee
  - left_foot
- bvh_depth_drivers:
  - RightFoot
  char_joints:
  - right_knee
  - right_foot
char_bvh_root_offset:
  bvh_projection_bodypart_group_for_offset: Lower Limbs
  bvh_joints:
  - - RightFoot
    - RightLeg
    - RightUpLeg
  - - LeftFoot
    - LeftLeg
    - LeftUpLeg
  char_joints:
  - - left_foot
    - left_knee
    - hip
  - - right_foot
    - right_knee
    - hip
char_joint_bvh_joints_mapping:
  left_foot: !!python/tuple
  - LeftLeg
  - LeftFoot
  left_knee: !!python/tuple
  - LeftUpLeg
  - LeftLeg
  right_foot: !!python/tuple
  - RightLeg
  - RightFoot
  right_knee: !!python/tuple
  - RightUpLeg
  - RightLeg
  neck: !!python/tuple
  - Hips
  - Neck
char_runtime_checks: []
